#!/bin/bash

echo "GENERATE NEW PROJECT"
mvn clean integration-test

echo "PACKAGE THE OUTPUT"
cd target/test-classes/projects/basic/project/projectx
git init
git add .
git commit -m init
git tag -a 0.1 -m init
chmod +x package
./package
cd -
