#!/bin/bash

POM_FILE="../pom.xml"
SCRIPT_PARAMS="$@"

source "../scripts/functions.sh"

set_term_title "Creating Package: mvn -Dvault.useProxy=false -DskipTests clean package"

mvn -Dvault.useProxy=false -DskipTests clean package

set_term_title "Created"

