#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

${symbol_pound} WARNING: Reference to these path is hardcoded into component dialogs
asset/rendition/prefix:
  prefixes:
    - thumbnail
    - web
  valueFormat: 'cq5dam.%%prefix%%.'
  title: 'OOTB %%prefix_normalised%%'

asset/license/format:
  contents:
    - metadata: {
      title: "Metadata: [Creator] [Contributor] [License] [Copyright Owner] [Expiry]",
      value: '<span itemprop="creator" itemtype="https://schema.org/Person">${symbol_dollar}{dc:creator}</span><span itemprop="contributor" itemtype="https://schema.org/Person">${symbol_dollar}{dc:contributor}</span><span itemprop="license" itemtype="https://schema.org/CreativeWork">${symbol_dollar}{dc:rights}</span><span itemprop="copyrightHolder" itemtype="https://schema.org/Person">${symbol_dollar}{xmpRights:Owner}</span><span itemprop="copyrightHolder" itemtype="https://schema.org/CreativeWork">${symbol_dollar}{prism:expirationDate}</span>'
    }
    - simple: {
      title: "Text: [Expiry] [Creator] [Contributor] [License] [Copyright Owner]",
      value: "${symbol_dollar}{prism:expirationDate} ${symbol_dollar}{dc:creator} ${symbol_dollar}{dc:contributor} ${symbol_dollar}{dc:rights} ${symbol_dollar}{xmpRights:Owner}"
    }

${symbol_pound} WARNING: Reference to these path is hardcoded into component dialogs
css/mediaquery:
  contents:
    - medium: {
      title: "Medium",
      value: "(min-width: 768px)"
    }
    - retina: {
      title: "Retina",
      value: "(-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 1.5dppx)"
    }
    - landscape-large: {
      title: "Landscape Large",
      value: "(min-width: 768px) and (orientation: landscape), screen and (min-width: 992px)"
    }
    - extra-large: {
      title: "Extra Large",
      value: "(min-width: 1200px)"
    }
    - retina-medium: {
      title: "Retina Medium",
      value: "(min-width: 768px) and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-width: 768px) and (min-resolution: 1.5dppx)"
    }
    - retina-landscape-large: {
      title: "Retina Landscape",
      value: "(min-width: 768px) and (orientation: landscape) and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-width: 768px) and (orientation: landscape) and (min-resolution: 1.5dppx), only screen and (min-width: 992px) and (min-device-pixel-ratio: 2)"
    }
    - retina-extra-large: {
      title: "Retina Extra Large",
      value: "(min-width: 1200px) and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-width: 1200px) and (min-resolution: 1.5dppx)"
    }

${symbol_pound} WARNING: Reference to these path is hardcoded into component dialogs
common/true-false:
  prefixes:
    - 'false'
    - 'true'
  valueFormat: '%%prefix%%'
  title: '%%prefix_normalised%%'

${symbol_pound} WARNING: Reference to these path is hardcoded into component dialogs
honorific/prefix:
  prefixes:
    - dr
    - lady
    - miss
    - mr
    - mrs
    - ms
    - sir
  valueFormat: '%%prefix%%'
  title: '%%prefix_normalised%%'

${symbol_pound} WARNING: Reference to these path is hardcoded into component dialogs
honorific/suffix:
  prefixes:
    - none
  valueFormat: '.'
  title: '%%prefix_normalised%%'
