#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )



  ${symbol_pound} Chevron
content/cq:tags/${contentFolderName}/component-style-chevron: &component-style-chevron
  chevron:
    prefixes:
      - circle-down
      - circle-up
      - circle-right
      - circle-left
      - down
      - up
      - right
      - left
    valueFormat: fa fa-chevron-%%prefix%%
    title: '%%prefix_normalised%%'




${symbol_pound} Showcase Copy
content/cq:tags/${contentFolderName}-showcase/component-style-chevron: *component-style-chevron

${symbol_pound} Training Copy
content/cq:tags/${contentFolderName}-training/component-style-chevron: *component-style-chevron
