#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )


${symbol_pound} Component Topic
content/cq:tags/${contentFolderName}/component-topic: &component-topic
  ${symbol_pound}used for comms between components
  group:
    prefixes:
      - group1
      - group2
    title: '%%prefix_normalised%%'

  ${symbol_pound}used for comms between components
  topic:
    prefixes:
      - eventFilterSelected         ${symbol_pound}when a selection in tag list is made
      - mapMarkerFilterSelected     ${symbol_pound}when map marker is filtered
    title: '%%prefix_normalised%%'



${symbol_pound} Showcase Copy
content/cq:tags/${contentFolderName}-showcase/component-topic: *component-topic

${symbol_pound} Training Copy
content/cq:tags/${contentFolderName}-training/component-topic: *component-topic
