#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

content/_cq_tags/${contentFolderName}/component-aria: &component-aria
  live:
    prefixes:
      - assertive
      - off
      - polite
    valueFormat: '%%prefix%%'
    title: '%%prefix_normalised%%'

  role:
    prefixes:
      - article
      - banner
      - complementary
      - contentinfo
      - navigation
      - toolbar
      - tooltip
    valueFormat: '%%prefix%%'
    title: '%%prefix_normalised%%'

${symbol_pound} Extends to
content/_cq_tags/${contentFolderName}-showcase/component-aria: *component-aria
content/_cq_tags/${contentFolderName}-training/component-aria: *component-aria
