#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

content/_cq_tags/${contentFolderName}/component-style-icon: &component-style-icon
  feed/atom:
    flat: true
    prefix: 'fa fa-rss'
    title: 'Atom'

  feed/rss:
    flat: true
    prefix: 'fa fa-rss'
    title: 'RSS'

  social:
    prefixes:
      - facebook
      - facebook-f
      - instagram
      - linkedin
      - linkedin-in
      - pinterest-p
      - tumblr
      - tumblr-square
      - twitter
      - youtube
    valueFormat: fab fa-%%prefix%%
    title: '%%prefix_normalised%%'

  spinner:
    prefixes:
      - cog
      - spinner
    valueFormat: fa fa-%%prefix%%
    title: '%%prefix_normalised%%'

  general:
    prefixes:
      - balance-scale
      - bars
      - book
      - briefcase
      - building
      - calculator
      - calendar
      - calendar-alt
      - car
      - chalkboard-teacher
      - chart-bar
      - child
      - code
      - cogs
      - comment-alt-check
      - comment-alt-dots
      - comment-alt-exclamation
      - comment-alt-smile
      - comments
      - comments-alt
      - connectdevelop
      - chevron-left
      - chevron-right
      - edit
      - envelope
      - fast-forward
      - flask
      - gamepad
      - gavel
      - globe
      - graduation-cap
      - heartbeat
      - home
      - info-circle
      - laptop
      - life-ring
      - link
      - location-circle
      - map
      - map-pin
      - newspaper
      - paper-plane
      - pencil-alt
      - phone
      - plane-arrival
      - plane-departure
      - play-circle
      - reply-all
      - school
      - search
      - star
      - star
      - stethoscope
      - street-view
      - times
      - thumbs-down
      - thumbs-up
      - train
      - trophy
      - university
      - user
      - user-graduate
      - users
      - users-class
      - video
      - wheelchair
      - wrench
      - handshake-alt
    valueFormat: fal fa-%%prefix%%
    title: '%%prefix_normalised%%'


${symbol_pound} Showcase Copy
content/_cq_tags/${contentFolderName}-showcase/component-style-icon: *component-style-icon

${symbol_pound} Training Copy
content/_cq_tags/${contentFolderName}-training/component-style-icon: *component-style-icon
