#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

content/_cq_tags/${contentFolderName}/component-style-module: &component-style-module
  ${symbol_pound} Generic
  generic/hide-on-search:
    flat: true
    prefix: hide-on-search
    title: 'Hide On Page Search'

  media/video/background:
    flat: true
    prefix: play-video
    title: 'Play Background Video'

  media/video/popup:
    flat: true
    prefix: play-video
    title: 'Play Popup Video'

  layout/contentblock/parallaximage:
    flat: true
    prefix: parallaximage
    title: 'Parallax Image'

  layout/button/navtoggler:
    flat: true
    prefix: navtoggler
    title: 'Nav Toggler (button)'

  ${symbol_pound} Search widget
  widgets/search/global-search:
    flat: true
    prefix: global-search
    title: 'Global Search'

  widgets/search/quicksearch:
    flat: true
    prefix: search
    title: 'Quick Search'

  widgets/search/header-search:
    flat: true
    prefix: header-search
    title: 'Header Search'

  ${symbol_pound} Carousel
  lists/carousel:
    flat: true
    prefix: carousel
    title: 'Carousel'

  ${symbol_pound} Load More
  lists/pagination/loadmore:
    flat: true
    prefix: loadmore
    title: 'Load More'

  lists/locationlist/map:
    flat: true
    prefix: map
    title: 'Map'




${symbol_pound} Showcase Copy
content/_cq_tags/${contentFolderName}-showcase/component-style-module: *component-style-module

${symbol_pound} Training Copy
content/_cq_tags/${contentFolderName}-training/component-style-module: *component-style-module
