#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

content/_cq_tags/${contentFolderName}/component-style-modifier: &component-style-modifier
  !!import/merge [
      'component-style-modifier/accessibility.yml',
      'component-style-modifier/button.yml',
      'component-style-modifier/card.yml',
      'component-style-modifier/colours.yml',
      'component-style-modifier/embed.yml',
      'component-style-modifier/flex.yml',
      'component-style-modifier/grid.yml',
      'component-style-modifier/icon.yml',
      'component-style-modifier/schema.yml',
      'component-style-modifier/spacing-area.yml',
      'component-style-modifier/text.yml',
  ]

${symbol_pound} Showcase Copy
content/_cq_tags/${contentFolderName}-showcase/component-style-modifier: *component-style-modifier

${symbol_pound} Training Copy
content/_cq_tags/${contentFolderName}-training/component-style-modifier: *component-style-modifier
