#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

content/_cq_tags/${contentFolderName}//component-dialog: &component-dialog
  !!import/merge [
      'component-dialog/general.yml',
      'component-dialog/html.yml',
      'component-dialog/components.yml',
      'component-dialog/components.lists.yml',
      'component-dialog/vue.yml',
  ]

${symbol_pound} Showcase Copy
content/_cq_tags/${contentFolderName}-showcase/component-dialog: *component-dialog

${symbol_pound} Training Copy
content/_cq_tags/${contentFolderName}-training/component-dialog: *component-dialog
